# Copyright (c) The Diem Core Contributors
# SPDX-License-Identifier: Apache-2.0
[tool.black]
line-length = 120
target-version = ['py35']
include = '\.pyi?$'
exclude = '''
(
  ^.+_pb2.py$ # ignore proto generated files
  | ^.+_grpc.py$ # ignore grpc generated files
)
'''
