"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Amount(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    AMOUNT_FIELD_NUMBER: builtins.int
    CURRENCY_FIELD_NUMBER: builtins.int
    amount: builtins.int = ...
    currency: typing.Text = ...
    def __init__(
        self,
        *,
        amount: builtins.int = ...,
        currency: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["amount", b"amount", "currency", b"currency"]
    ) -> None: ...

global___Amount = Amount

class Account(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ADDRESS_FIELD_NUMBER: builtins.int
    BALANCES_FIELD_NUMBER: builtins.int
    SEQUENCE_NUMBER_FIELD_NUMBER: builtins.int
    AUTHENTICATION_KEY_FIELD_NUMBER: builtins.int
    SENT_EVENTS_KEY_FIELD_NUMBER: builtins.int
    RECEIVED_EVENTS_KEY_FIELD_NUMBER: builtins.int
    DELEGATED_KEY_ROTATION_CAPABILITY_FIELD_NUMBER: builtins.int
    DELEGATED_WITHDRAWAL_CAPABILITY_FIELD_NUMBER: builtins.int
    IS_FROZEN_FIELD_NUMBER: builtins.int
    ROLE_FIELD_NUMBER: builtins.int
    address: typing.Text = ...
    sequence_number: builtins.int = ...
    authentication_key: typing.Text = ...
    sent_events_key: typing.Text = ...
    received_events_key: typing.Text = ...
    delegated_key_rotation_capability: builtins.bool = ...
    delegated_withdrawal_capability: builtins.bool = ...
    is_frozen: builtins.bool = ...
    @property
    def balances(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Amount]: ...
    @property
    def role(self) -> global___AccountRole: ...
    def __init__(
        self,
        *,
        address: typing.Text = ...,
        balances: typing.Optional[typing.Iterable[global___Amount]] = ...,
        sequence_number: builtins.int = ...,
        authentication_key: typing.Text = ...,
        sent_events_key: typing.Text = ...,
        received_events_key: typing.Text = ...,
        delegated_key_rotation_capability: builtins.bool = ...,
        delegated_withdrawal_capability: builtins.bool = ...,
        is_frozen: builtins.bool = ...,
        role: typing.Optional[global___AccountRole] = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["role", b"role"]) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "address",
            b"address",
            "authentication_key",
            b"authentication_key",
            "balances",
            b"balances",
            "delegated_key_rotation_capability",
            b"delegated_key_rotation_capability",
            "delegated_withdrawal_capability",
            b"delegated_withdrawal_capability",
            "is_frozen",
            b"is_frozen",
            "received_events_key",
            b"received_events_key",
            "role",
            b"role",
            "sent_events_key",
            b"sent_events_key",
            "sequence_number",
            b"sequence_number",
        ],
    ) -> None: ...

global___Account = Account

class AccountRole(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TYPE_FIELD_NUMBER: builtins.int
    PARENT_VASP_ADDRESS_FIELD_NUMBER: builtins.int
    HUMAN_NAME_FIELD_NUMBER: builtins.int
    BASE_URL_FIELD_NUMBER: builtins.int
    EXPIRATION_TIME_FIELD_NUMBER: builtins.int
    COMPLIANCE_KEY_FIELD_NUMBER: builtins.int
    COMPLIANCE_KEY_ROTATION_EVENTS_KEY_FIELD_NUMBER: builtins.int
    BASE_URL_ROTATION_EVENTS_KEY_FIELD_NUMBER: builtins.int
    NUM_CHILDREN_FIELD_NUMBER: builtins.int
    RECEIVED_MINT_EVENTS_KEY_FIELD_NUMBER: builtins.int
    PREBURN_BALANCES_FIELD_NUMBER: builtins.int
    type: typing.Text = ...
    parent_vasp_address: typing.Text = ...
    human_name: typing.Text = ...
    base_url: typing.Text = ...
    expiration_time: builtins.int = ...
    compliance_key: typing.Text = ...
    compliance_key_rotation_events_key: typing.Text = ...
    base_url_rotation_events_key: typing.Text = ...
    num_children: builtins.int = ...
    received_mint_events_key: typing.Text = ...
    @property
    def preburn_balances(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Amount]: ...
    def __init__(
        self,
        *,
        type: typing.Text = ...,
        parent_vasp_address: typing.Text = ...,
        human_name: typing.Text = ...,
        base_url: typing.Text = ...,
        expiration_time: builtins.int = ...,
        compliance_key: typing.Text = ...,
        compliance_key_rotation_events_key: typing.Text = ...,
        base_url_rotation_events_key: typing.Text = ...,
        num_children: builtins.int = ...,
        received_mint_events_key: typing.Text = ...,
        preburn_balances: typing.Optional[typing.Iterable[global___Amount]] = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "base_url",
            b"base_url",
            "base_url_rotation_events_key",
            b"base_url_rotation_events_key",
            "compliance_key",
            b"compliance_key",
            "compliance_key_rotation_events_key",
            b"compliance_key_rotation_events_key",
            "expiration_time",
            b"expiration_time",
            "human_name",
            b"human_name",
            "num_children",
            b"num_children",
            "parent_vasp_address",
            b"parent_vasp_address",
            "preburn_balances",
            b"preburn_balances",
            "received_mint_events_key",
            b"received_mint_events_key",
            "type",
            b"type",
        ],
    ) -> None: ...

global___AccountRole = AccountRole

class Event(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    KEY_FIELD_NUMBER: builtins.int
    SEQUENCE_NUMBER_FIELD_NUMBER: builtins.int
    TRANSACTION_VERSION_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    key: typing.Text = ...
    sequence_number: builtins.int = ...
    transaction_version: builtins.int = ...
    @property
    def data(self) -> global___EventData: ...
    def __init__(
        self,
        *,
        key: typing.Text = ...,
        sequence_number: builtins.int = ...,
        transaction_version: builtins.int = ...,
        data: typing.Optional[global___EventData] = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["data", b"data"]) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "data",
            b"data",
            "key",
            b"key",
            "sequence_number",
            b"sequence_number",
            "transaction_version",
            b"transaction_version",
        ],
    ) -> None: ...

global___Event = Event

class EventData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TYPE_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    PREBURN_ADDRESS_FIELD_NUMBER: builtins.int
    CURRENCY_CODE_FIELD_NUMBER: builtins.int
    NEW_TO_XDX_EXCHANGE_RATE_FIELD_NUMBER: builtins.int
    SENDER_FIELD_NUMBER: builtins.int
    RECEIVER_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    EPOCH_FIELD_NUMBER: builtins.int
    ROUND_FIELD_NUMBER: builtins.int
    PROPOSER_FIELD_NUMBER: builtins.int
    PROPOSED_TIME_FIELD_NUMBER: builtins.int
    DESTINATION_ADDRESS_FIELD_NUMBER: builtins.int
    NEW_COMPLIANCE_PUBLIC_KEY_FIELD_NUMBER: builtins.int
    NEW_BASE_URL_FIELD_NUMBER: builtins.int
    TIME_ROTATED_SECONDS_FIELD_NUMBER: builtins.int
    CREATED_ADDRESS_FIELD_NUMBER: builtins.int
    ROLE_ID_FIELD_NUMBER: builtins.int
    COMMITTED_TIMESTAMP_SECS_FIELD_NUMBER: builtins.int
    type: typing.Text = ...
    preburn_address: typing.Text = ...
    currency_code: typing.Text = ...
    new_to_xdx_exchange_rate: builtins.float = ...
    sender: typing.Text = ...
    receiver: typing.Text = ...
    metadata: typing.Text = ...
    epoch: builtins.int = ...
    round: builtins.int = ...
    proposer: typing.Text = ...
    proposed_time: builtins.int = ...
    destination_address: typing.Text = ...
    new_compliance_public_key: typing.Text = ...
    new_base_url: typing.Text = ...
    time_rotated_seconds: builtins.int = ...
    created_address: typing.Text = ...
    role_id: builtins.int = ...
    committed_timestamp_secs: builtins.int = ...
    @property
    def amount(self) -> global___Amount: ...
    def __init__(
        self,
        *,
        type: typing.Text = ...,
        amount: typing.Optional[global___Amount] = ...,
        preburn_address: typing.Text = ...,
        currency_code: typing.Text = ...,
        new_to_xdx_exchange_rate: builtins.float = ...,
        sender: typing.Text = ...,
        receiver: typing.Text = ...,
        metadata: typing.Text = ...,
        epoch: builtins.int = ...,
        round: builtins.int = ...,
        proposer: typing.Text = ...,
        proposed_time: builtins.int = ...,
        destination_address: typing.Text = ...,
        new_compliance_public_key: typing.Text = ...,
        new_base_url: typing.Text = ...,
        time_rotated_seconds: builtins.int = ...,
        created_address: typing.Text = ...,
        role_id: builtins.int = ...,
        committed_timestamp_secs: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["amount", b"amount"]) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "amount",
            b"amount",
            "committed_timestamp_secs",
            b"committed_timestamp_secs",
            "created_address",
            b"created_address",
            "currency_code",
            b"currency_code",
            "destination_address",
            b"destination_address",
            "epoch",
            b"epoch",
            "metadata",
            b"metadata",
            "new_base_url",
            b"new_base_url",
            "new_compliance_public_key",
            b"new_compliance_public_key",
            "new_to_xdx_exchange_rate",
            b"new_to_xdx_exchange_rate",
            "preburn_address",
            b"preburn_address",
            "proposed_time",
            b"proposed_time",
            "proposer",
            b"proposer",
            "receiver",
            b"receiver",
            "role_id",
            b"role_id",
            "round",
            b"round",
            "sender",
            b"sender",
            "time_rotated_seconds",
            b"time_rotated_seconds",
            "type",
            b"type",
        ],
    ) -> None: ...

global___EventData = EventData

class Metadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    VERSION_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    CHAIN_ID_FIELD_NUMBER: builtins.int
    SCRIPT_HASH_ALLOW_LIST_FIELD_NUMBER: builtins.int
    MODULE_PUBLISHING_ALLOWED_FIELD_NUMBER: builtins.int
    DIEM_VERSION_FIELD_NUMBER: builtins.int
    ACCUMULATOR_ROOT_HASH_FIELD_NUMBER: builtins.int
    DUAL_ATTESTATION_LIMIT_FIELD_NUMBER: builtins.int
    version: builtins.int = ...
    timestamp: builtins.int = ...
    chain_id: builtins.int = ...
    script_hash_allow_list: google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text] = ...
    module_publishing_allowed: builtins.bool = ...
    diem_version: builtins.int = ...
    accumulator_root_hash: typing.Text = ...
    dual_attestation_limit: builtins.int = ...
    def __init__(
        self,
        *,
        version: builtins.int = ...,
        timestamp: builtins.int = ...,
        chain_id: builtins.int = ...,
        script_hash_allow_list: typing.Optional[typing.Iterable[typing.Text]] = ...,
        module_publishing_allowed: builtins.bool = ...,
        diem_version: builtins.int = ...,
        accumulator_root_hash: typing.Text = ...,
        dual_attestation_limit: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "accumulator_root_hash",
            b"accumulator_root_hash",
            "chain_id",
            b"chain_id",
            "diem_version",
            b"diem_version",
            "dual_attestation_limit",
            b"dual_attestation_limit",
            "module_publishing_allowed",
            b"module_publishing_allowed",
            "script_hash_allow_list",
            b"script_hash_allow_list",
            "timestamp",
            b"timestamp",
            "version",
            b"version",
        ],
    ) -> None: ...

global___Metadata = Metadata

class Transaction(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    VERSION_FIELD_NUMBER: builtins.int
    TRANSACTION_FIELD_NUMBER: builtins.int
    HASH_FIELD_NUMBER: builtins.int
    BYTES_FIELD_NUMBER: builtins.int
    EVENTS_FIELD_NUMBER: builtins.int
    VM_STATUS_FIELD_NUMBER: builtins.int
    GAS_USED_FIELD_NUMBER: builtins.int
    version: builtins.int = ...
    hash: typing.Text = ...
    bytes: typing.Text = ...
    gas_used: builtins.int = ...
    @property
    def transaction(self) -> global___TransactionData: ...
    @property
    def events(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Event]: ...
    @property
    def vm_status(self) -> global___VMStatus: ...
    def __init__(
        self,
        *,
        version: builtins.int = ...,
        transaction: typing.Optional[global___TransactionData] = ...,
        hash: typing.Text = ...,
        bytes: typing.Text = ...,
        events: typing.Optional[typing.Iterable[global___Event]] = ...,
        vm_status: typing.Optional[global___VMStatus] = ...,
        gas_used: builtins.int = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["transaction", b"transaction", "vm_status", b"vm_status"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "bytes",
            b"bytes",
            "events",
            b"events",
            "gas_used",
            b"gas_used",
            "hash",
            b"hash",
            "transaction",
            b"transaction",
            "version",
            b"version",
            "vm_status",
            b"vm_status",
        ],
    ) -> None: ...

global___Transaction = Transaction

class MoveAbortExplaination(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CATEGORY_FIELD_NUMBER: builtins.int
    CATEGORY_DESCRIPTION_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    REASON_DESCRIPTION_FIELD_NUMBER: builtins.int
    category: typing.Text = ...
    category_description: typing.Text = ...
    reason: typing.Text = ...
    reason_description: typing.Text = ...
    def __init__(
        self,
        *,
        category: typing.Text = ...,
        category_description: typing.Text = ...,
        reason: typing.Text = ...,
        reason_description: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "category",
            b"category",
            "category_description",
            b"category_description",
            "reason",
            b"reason",
            "reason_description",
            b"reason_description",
        ],
    ) -> None: ...

global___MoveAbortExplaination = MoveAbortExplaination

class VMStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TYPE_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    ABORT_CODE_FIELD_NUMBER: builtins.int
    FUNCTION_INDEX_FIELD_NUMBER: builtins.int
    CODE_OFFSET_FIELD_NUMBER: builtins.int
    EXPLANATION_FIELD_NUMBER: builtins.int
    type: typing.Text = ...
    location: typing.Text = ...
    abort_code: builtins.int = ...
    function_index: builtins.int = ...
    code_offset: builtins.int = ...
    @property
    def explanation(self) -> global___MoveAbortExplaination: ...
    def __init__(
        self,
        *,
        type: typing.Text = ...,
        location: typing.Text = ...,
        abort_code: builtins.int = ...,
        function_index: builtins.int = ...,
        code_offset: builtins.int = ...,
        explanation: typing.Optional[global___MoveAbortExplaination] = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["explanation", b"explanation"]) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "abort_code",
            b"abort_code",
            "code_offset",
            b"code_offset",
            "explanation",
            b"explanation",
            "function_index",
            b"function_index",
            "location",
            b"location",
            "type",
            b"type",
        ],
    ) -> None: ...

global___VMStatus = VMStatus

class TransactionData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TYPE_FIELD_NUMBER: builtins.int
    TIMESTAMP_USECS_FIELD_NUMBER: builtins.int
    SENDER_FIELD_NUMBER: builtins.int
    SIGNATURE_SCHEME_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    PUBLIC_KEY_FIELD_NUMBER: builtins.int
    SEQUENCE_NUMBER_FIELD_NUMBER: builtins.int
    CHAIN_ID_FIELD_NUMBER: builtins.int
    MAX_GAS_AMOUNT_FIELD_NUMBER: builtins.int
    GAS_UNIT_PRICE_FIELD_NUMBER: builtins.int
    GAS_CURRENCY_FIELD_NUMBER: builtins.int
    EXPIRATION_TIMESTAMP_SECS_FIELD_NUMBER: builtins.int
    SCRIPT_HASH_FIELD_NUMBER: builtins.int
    SCRIPT_BYTES_FIELD_NUMBER: builtins.int
    SCRIPT_FIELD_NUMBER: builtins.int
    type: typing.Text = ...
    timestamp_usecs: builtins.int = ...
    sender: typing.Text = ...
    signature_scheme: typing.Text = ...
    signature: typing.Text = ...
    public_key: typing.Text = ...
    sequence_number: builtins.int = ...
    chain_id: builtins.int = ...
    max_gas_amount: builtins.int = ...
    gas_unit_price: builtins.int = ...
    gas_currency: typing.Text = ...
    expiration_timestamp_secs: builtins.int = ...
    script_hash: typing.Text = ...
    script_bytes: typing.Text = ...
    @property
    def script(self) -> global___Script: ...
    def __init__(
        self,
        *,
        type: typing.Text = ...,
        timestamp_usecs: builtins.int = ...,
        sender: typing.Text = ...,
        signature_scheme: typing.Text = ...,
        signature: typing.Text = ...,
        public_key: typing.Text = ...,
        sequence_number: builtins.int = ...,
        chain_id: builtins.int = ...,
        max_gas_amount: builtins.int = ...,
        gas_unit_price: builtins.int = ...,
        gas_currency: typing.Text = ...,
        expiration_timestamp_secs: builtins.int = ...,
        script_hash: typing.Text = ...,
        script_bytes: typing.Text = ...,
        script: typing.Optional[global___Script] = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["script", b"script"]) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "chain_id",
            b"chain_id",
            "expiration_timestamp_secs",
            b"expiration_timestamp_secs",
            "gas_currency",
            b"gas_currency",
            "gas_unit_price",
            b"gas_unit_price",
            "max_gas_amount",
            b"max_gas_amount",
            "public_key",
            b"public_key",
            "script",
            b"script",
            "script_bytes",
            b"script_bytes",
            "script_hash",
            b"script_hash",
            "sender",
            b"sender",
            "sequence_number",
            b"sequence_number",
            "signature",
            b"signature",
            "signature_scheme",
            b"signature_scheme",
            "timestamp_usecs",
            b"timestamp_usecs",
            "type",
            b"type",
        ],
    ) -> None: ...

global___TransactionData = TransactionData

class Script(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TYPE_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    ARGUMENTS_FIELD_NUMBER: builtins.int
    TYPE_ARGUMENTS_FIELD_NUMBER: builtins.int
    RECEIVER_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    CURRENCY_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    METADATA_SIGNATURE_FIELD_NUMBER: builtins.int
    type: typing.Text = ...
    code: typing.Text = ...
    arguments: google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text] = ...
    type_arguments: google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text] = ...
    receiver: typing.Text = ...
    amount: builtins.int = ...
    currency: typing.Text = ...
    metadata: typing.Text = ...
    metadata_signature: typing.Text = ...
    def __init__(
        self,
        *,
        type: typing.Text = ...,
        code: typing.Text = ...,
        arguments: typing.Optional[typing.Iterable[typing.Text]] = ...,
        type_arguments: typing.Optional[typing.Iterable[typing.Text]] = ...,
        receiver: typing.Text = ...,
        amount: builtins.int = ...,
        currency: typing.Text = ...,
        metadata: typing.Text = ...,
        metadata_signature: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "amount",
            b"amount",
            "arguments",
            b"arguments",
            "code",
            b"code",
            "currency",
            b"currency",
            "metadata",
            b"metadata",
            "metadata_signature",
            b"metadata_signature",
            "receiver",
            b"receiver",
            "type",
            b"type",
            "type_arguments",
            b"type_arguments",
        ],
    ) -> None: ...

global___Script = Script

class CurrencyInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CODE_FIELD_NUMBER: builtins.int
    SCALING_FACTOR_FIELD_NUMBER: builtins.int
    FRACTIONAL_PART_FIELD_NUMBER: builtins.int
    TO_XDX_EXCHANGE_RATE_FIELD_NUMBER: builtins.int
    MINT_EVENTS_KEY_FIELD_NUMBER: builtins.int
    BURN_EVENTS_KEY_FIELD_NUMBER: builtins.int
    PREBURN_EVENTS_KEY_FIELD_NUMBER: builtins.int
    CANCEL_BURN_EVENTS_KEY_FIELD_NUMBER: builtins.int
    EXCHANGE_RATE_UPDATE_EVENTS_KEY_FIELD_NUMBER: builtins.int
    code: typing.Text = ...
    scaling_factor: builtins.int = ...
    fractional_part: builtins.int = ...
    to_xdx_exchange_rate: builtins.float = ...
    mint_events_key: typing.Text = ...
    burn_events_key: typing.Text = ...
    preburn_events_key: typing.Text = ...
    cancel_burn_events_key: typing.Text = ...
    exchange_rate_update_events_key: typing.Text = ...
    def __init__(
        self,
        *,
        code: typing.Text = ...,
        scaling_factor: builtins.int = ...,
        fractional_part: builtins.int = ...,
        to_xdx_exchange_rate: builtins.float = ...,
        mint_events_key: typing.Text = ...,
        burn_events_key: typing.Text = ...,
        preburn_events_key: typing.Text = ...,
        cancel_burn_events_key: typing.Text = ...,
        exchange_rate_update_events_key: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "burn_events_key",
            b"burn_events_key",
            "cancel_burn_events_key",
            b"cancel_burn_events_key",
            "code",
            b"code",
            "exchange_rate_update_events_key",
            b"exchange_rate_update_events_key",
            "fractional_part",
            b"fractional_part",
            "mint_events_key",
            b"mint_events_key",
            "preburn_events_key",
            b"preburn_events_key",
            "scaling_factor",
            b"scaling_factor",
            "to_xdx_exchange_rate",
            b"to_xdx_exchange_rate",
        ],
    ) -> None: ...

global___CurrencyInfo = CurrencyInfo

class StateProof(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LEDGER_INFO_WITH_SIGNATURES_FIELD_NUMBER: builtins.int
    EPOCH_CHANGE_PROOF_FIELD_NUMBER: builtins.int
    LEDGER_CONSISTENCY_PROOF_FIELD_NUMBER: builtins.int
    ledger_info_with_signatures: typing.Text = ...
    epoch_change_proof: typing.Text = ...
    ledger_consistency_proof: typing.Text = ...
    def __init__(
        self,
        *,
        ledger_info_with_signatures: typing.Text = ...,
        epoch_change_proof: typing.Text = ...,
        ledger_consistency_proof: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "epoch_change_proof",
            b"epoch_change_proof",
            "ledger_consistency_proof",
            b"ledger_consistency_proof",
            "ledger_info_with_signatures",
            b"ledger_info_with_signatures",
        ],
    ) -> None: ...

global___StateProof = StateProof

class AccountStateWithProof(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    VERSION_FIELD_NUMBER: builtins.int
    BLOB_FIELD_NUMBER: builtins.int
    PROOF_FIELD_NUMBER: builtins.int
    version: builtins.int = ...
    blob: typing.Text = ...
    @property
    def proof(self) -> global___AccountStateProof: ...
    def __init__(
        self,
        *,
        version: builtins.int = ...,
        blob: typing.Text = ...,
        proof: typing.Optional[global___AccountStateProof] = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["proof", b"proof"]) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["blob", b"blob", "proof", b"proof", "version", b"version"]
    ) -> None: ...

global___AccountStateWithProof = AccountStateWithProof

class AccountStateProof(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LEDGER_INFO_TO_TRANSACTION_INFO_PROOF_FIELD_NUMBER: builtins.int
    TRANSACTION_INFO_FIELD_NUMBER: builtins.int
    TRANSACTION_INFO_TO_ACCOUNT_PROOF_FIELD_NUMBER: builtins.int
    ledger_info_to_transaction_info_proof: typing.Text = ...
    transaction_info: typing.Text = ...
    transaction_info_to_account_proof: typing.Text = ...
    def __init__(
        self,
        *,
        ledger_info_to_transaction_info_proof: typing.Text = ...,
        transaction_info: typing.Text = ...,
        transaction_info_to_account_proof: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "ledger_info_to_transaction_info_proof",
            b"ledger_info_to_transaction_info_proof",
            "transaction_info",
            b"transaction_info",
            "transaction_info_to_account_proof",
            b"transaction_info_to_account_proof",
        ],
    ) -> None: ...

global___AccountStateProof = AccountStateProof
