from typing import Any

class AdmissionControlStub:
    SubmitTransaction: Any = ...
    UpdateToLatestLedger: Any = ...
    def __init__(self, channel: Any) -> None: ...

class AdmissionControlServicer:
    def SubmitTransaction(self, request: Any, context: Any) -> None: ...
    def UpdateToLatestLedger(self, request: Any, context: Any) -> None: ...

def add_AdmissionControlServicer_to_server(servicer: Any, server: Any) -> None: ...
