# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mempool_status.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mempool_status.proto',
  package='mempool_status',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14mempool_status.proto\x12\x0emempool_status\"m\n\x1bMempoolAddTransactionStatus\x12=\n\x04\x63ode\x18\x01 \x01(\x0e\x32/.mempool_status.MempoolAddTransactionStatusCode\x12\x0f\n\x07message\x18\x02 \x01(\t*\x9a\x01\n\x1fMempoolAddTransactionStatusCode\x12\t\n\x05Valid\x10\x00\x12\x17\n\x13InsufficientBalance\x10\x01\x12\x14\n\x10InvalidSeqNumber\x10\x02\x12\x11\n\rMempoolIsFull\x10\x03\x12\x17\n\x13TooManyTransactions\x10\x04\x12\x11\n\rInvalidUpdate\x10\x05\x62\x06proto3')
)

_MEMPOOLADDTRANSACTIONSTATUSCODE = _descriptor.EnumDescriptor(
  name='MempoolAddTransactionStatusCode',
  full_name='mempool_status.MempoolAddTransactionStatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Valid', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='InsufficientBalance', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='InvalidSeqNumber', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MempoolIsFull', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TooManyTransactions', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='InvalidUpdate', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=152,
  serialized_end=306,
)
_sym_db.RegisterEnumDescriptor(_MEMPOOLADDTRANSACTIONSTATUSCODE)

MempoolAddTransactionStatusCode = enum_type_wrapper.EnumTypeWrapper(_MEMPOOLADDTRANSACTIONSTATUSCODE)
Valid = 0
InsufficientBalance = 1
InvalidSeqNumber = 2
MempoolIsFull = 3
TooManyTransactions = 4
InvalidUpdate = 5



_MEMPOOLADDTRANSACTIONSTATUS = _descriptor.Descriptor(
  name='MempoolAddTransactionStatus',
  full_name='mempool_status.MempoolAddTransactionStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='mempool_status.MempoolAddTransactionStatus.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='mempool_status.MempoolAddTransactionStatus.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=149,
)

_MEMPOOLADDTRANSACTIONSTATUS.fields_by_name['code'].enum_type = _MEMPOOLADDTRANSACTIONSTATUSCODE
DESCRIPTOR.message_types_by_name['MempoolAddTransactionStatus'] = _MEMPOOLADDTRANSACTIONSTATUS
DESCRIPTOR.enum_types_by_name['MempoolAddTransactionStatusCode'] = _MEMPOOLADDTRANSACTIONSTATUSCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MempoolAddTransactionStatus = _reflection.GeneratedProtocolMessageType('MempoolAddTransactionStatus', (_message.Message,), {
  'DESCRIPTOR' : _MEMPOOLADDTRANSACTIONSTATUS,
  '__module__' : 'mempool_status_pb2'
  # @@protoc_insertion_point(class_scope:mempool_status.MempoolAddTransactionStatus)
  })
_sym_db.RegisterMessage(MempoolAddTransactionStatus)


# @@protoc_insertion_point(module_scope)
