# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vm_errors.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import language_storage_pb2 as language__storage__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='vm_errors.proto',
  package='types',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fvm_errors.proto\x12\x05types\x1a\x16language_storage.proto\"r\n\x08VMStatus\x12\x14\n\x0cmajor_status\x18\x01 \x01(\x04\x12\x16\n\x0ehas_sub_status\x18\x02 \x01(\x08\x12\x12\n\nsub_status\x18\x03 \x01(\x04\x12\x13\n\x0bhas_message\x18\x04 \x01(\x08\x12\x0f\n\x07message\x18\x05 \x01(\tb\x06proto3')
  ,
  dependencies=[language__storage__pb2.DESCRIPTOR,])




_VMSTATUS = _descriptor.Descriptor(
  name='VMStatus',
  full_name='types.VMStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='major_status', full_name='types.VMStatus.major_status', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='has_sub_status', full_name='types.VMStatus.has_sub_status', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sub_status', full_name='types.VMStatus.sub_status', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='has_message', full_name='types.VMStatus.has_message', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='types.VMStatus.message', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=164,
)

DESCRIPTOR.message_types_by_name['VMStatus'] = _VMSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VMStatus = _reflection.GeneratedProtocolMessageType('VMStatus', (_message.Message,), {
  'DESCRIPTOR' : _VMSTATUS,
  '__module__' : 'vm_errors_pb2'
  # @@protoc_insertion_point(class_scope:types.VMStatus)
  })
_sym_db.RegisterMessage(VMStatus)


# @@protoc_insertion_point(module_scope)
