version: "3.8"
x-services-volume:
  &services-volume
  - type: volume
    source: db
    target: /opt/diem/var
  - type: bind
    source: ./root.key
    target: /opt/diem/var/root.key
services:
    validator:
        image: diem/validator:release-1.1_ab1761a8
        volumes: *services-volume
        command: ["/opt/diem/bin/diem-node", "--test", "--config", "/opt/diem/var"]
        ports:
            - "8080:8080"
    faucet:
        image: diem/faucet:release-1.1_ab1761a8
        volumes: *services-volume
        command: [
            "/opt/diem/bin/diem-faucet",
            "-a",
            "0.0.0.0",
            "-p",
            "8000",
            "--server-url",
            "http://validator:8080/v1",
            "-m",
            "/opt/diem/var/root.key",
            "-c",
            "4",
        ]
        ports:
            - "8000:8000"
volumes:
    db:
